### ISSUE TITLE
Congrats! - Licensing

### ISSUE THREAD

**Issue by hipsterusername** [AndyShih12/paradigms#1]
We'd love to incorporate this into InvokeAI, but would like to request a license be added so we know how (and whether) we can use it.

Thanks for the excellent work, and congrats on the accomplishment @AndyShih12 et. al

**Comment by AndyShih12** [comment]
Ok, added a license: 4a72027682238dbaec163b44fa0cae006ca804cd

Thank you!

**Comment by hipsterusername** [comment]
Thank **you**!
