### ISSUE TITLE
How to Implement Paradigms Sampler to Automatic 1111

### ISSUE THREAD

**Issue by gjin10969** [AndyShih12/paradigms#2]
How to Implement Paradigms Sampler to Automatic 1111

![image](https://github.com/AndyShih12/paradigms/assets/113190973/41b60848-2824-4d2e-b944-4454853bae95)

https://github.com/AndyShih12/paradigms

**Comment by AndyShih12** [comment]
Could you please be more specific? I don't understand your question.
