### ISSUE TITLE
Inpainting

### ISSUE THREAD

**Issue by landmann** [AndyShih12/paradigms#3]
Is it possible to run this with inpainting?

Also, any noticeable deterioration of images?

Thanks for your work!

**Comment by AndyShih12** [comment]
Yes, it is possible to run the same parallel sampling algorithm for inpainting, though it is not implemented yet.
You just have to follow the same algorithm as the one [here](https://github.com/AndyShih12/paradigms/blob/47b870c766408fd8d1c3e8c78c12a369d462200f/paradigms/stablediffusion_paradigms.py#L190).

And no, there should not be deterioration of images if the [tolerance](https://github.com/AndyShih12/paradigms/blob/47b870c766408fd8d1c3e8c78c12a369d462200f/paradigms/stablediffusion_paradigms.py#L15) is tuned correctly.

**Comment by landmann** [comment]
Very cool - will look into it. And what about other schedulers like DPM+ Karras etc?? 

Or does it only work with DDPM?

**Comment by AndyShih12** [comment]
Thanks for trying out our code.

In terms of schedulers, currently Diffusers only has ParaDDPM and ParaDDIM. In this repo, we additionally have ParaDPMSolver. For the moment, you can use it like this:

```python
import torch
from diffusers import DDPMParallelScheduler
from diffusers import StableDiffusionParadigmsPipeline

from paradigms.paradpmsolver_scheduler import ParaDPMSolverMultistepScheduler

scheduler = ParaDPMSolverMultistepScheduler.from_pretrained("runwayml/stable-diffusion-v1-5", subfolder="scheduler", timestep_spacing="trailing")
scheduler._is_ode_scheduler = True
scheduler._is_parallel = True
scheduler.config.thresholding = False

pipe = StableDiffusionParadigmsPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5", scheduler=scheduler, torch_dtype=torch.float16
)
pipe = pipe.to("cuda")
ngpu, batch_per_device = torch.cuda.device_count(), 5
pipe.wrapped_unet = torch.nn.DataParallel(pipe.unet, device_ids=[d for d in range(ngpu)])
prompt = "a photo of an astronaut riding a horse on mars"

image = pipe(prompt, parallel=ngpu * batch_per_device, num_inference_steps=200).images[0]
image.save("image.png")
```


Supporting other schedulers should be quite easy. Just implement a tensorized version of step() function like [here](https://github.com/AndyShih12/paradigms/blob/47b870c766408fd8d1c3e8c78c12a369d462200f/paradigms/paradpmsolver_scheduler.py#L23C17-L23C17) and a get_varance() function like [here](https://github.com/AndyShih12/paradigms/blob/47b870c766408fd8d1c3e8c78c12a369d462200f/paradigms/paradpmsolver_scheduler.py#L11C12-L11C12). The three examples of ParaDDPM, ParaDDIM, and ParaDPMScheduler in https://github.com/AndyShih12/paradigms/tree/master/paradigms should provide enough guidance.

**Comment by landmann** [comment]
Oh my pleasure, Andy! Thank you very much for this.

Btw, what are y'all working on nowadays? Would love to sponsor / collab with you guys in some way 🙂 You should DM me at nlandmanc@gmail.com.

**Comment by AndyShih12** [comment]
Still working on similar directions! Thanks, that's very nice of you 😄 we're currently managing well so you should pass it forward to others!
